dice.sides:
  - |
    +-------+
    |       |
    |   o   |
    |       |
    +-------+
  - |
    +-------+
    | o     |
    |       |
    |     o |
    +-------+
  - |
    +-------+
    | o     |
    |   o   |
    |     o |
    +-------+
  - |
    +-------+
    | o   o |
    |       |
    | o   o |
    +-------+
  - |
    +-------+
    | o   o |
    |   o   |
    | o   o |
    +-------+
  - |
    +-------+
    | o   o |
    | o   o |
    | o   o |
    +-------+
